# Generated by Django 4.2.7 on 2024-01-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_verification_code_alter_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.TextField(blank=True, null=True, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True, null=True, verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.TextField(blank=True, default='88779251', null=True, verbose_name='код подтверждения почты'),
        ),
    ]
