# Generated by Django 4.2.7 on 2023-11-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_product_price_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1, verbose_name='цена за покупку'),
            preserve_default=False,
        ),
    ]
