# Generated by Django 4.2.7 on 2023-12-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='слаг')),
                ('description', models.TextField(verbose_name='содержимое')),
                ('image', models.ImageField(upload_to='media/', verbose_name='изображение')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('publication', models.BooleanField(verbose_name='признак публикации')),
                ('views_count', models.IntegerField(default=0, verbose_name='колличество просмотров')),
            ],
            options={
                'verbose_name': 'блоговая запись',
                'verbose_name_plural': 'блоговые записи',
            },
        ),
    ]
