# Generated by Django 4.2.7 on 2023-12-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='publication',
            field=models.BooleanField(default=True, verbose_name='признак публикации'),
        ),
        migrations.AlterField(
            model_name='record',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='слаг'),
        ),
    ]
